export const LOGIN_START = 'LOGIN_START';
export const LOGIN_END = 'LOGIN_END';

export const LOGOUT = 'LOGOUT';

// export const READ_PROJECT_LIST_START = 'READ_PROJECT_LIST_START';
// export const READ_PROJECT_LIST_END = 'READ_PROJECT_LIST_END';
//
// export const CREATE_PROJECT_START = 'CREATE_PROJECT_START';
// export const CREATE_PROJECT_END = 'CREATE_PROJECT_END';
//
// export const READ_PROJECT_START = 'READ_PROJECT_START';
// export const READ_PROJECT_END = 'READ_PROJECT_END';
//
// export const CREATE_COMMENT_START = 'CREATE_COMMENT_START';
// export const CREATE_COMMENT_END = 'CREATE_COMMENT_END';
